apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-app
  template:
    metadata:
      labels:
        app: autoscale-app
    spec:
      containers:
      - name: autoscale-app
        image: <your-dockerhub-username>/autoscale-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
